# Generated by Django 4.0.4 on 2022-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='age',
            field=models.IntegerField(),
        ),
    ]
