# Generated by Django 4.0.4 on 2022-07-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_testing_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='age',
        ),
    ]
