# Generated by Django 4.0.4 on 2022-07-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_testing_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testing',
            new_name='TeamModel',
        ),
    ]
